name: Website Deployment
on: 
    push:
        branches:
            - master
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
